services:
  # Next.jsの環境
  view-prod:
    container_name: "hnz-view-prod"
    build:
      context: ./view
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true 
    env_file:
      - ./view/.env
    restart: unless-stopped
  cloudflare:
      image: "cloudflare/cloudflared:2025.2.1"
      container_name: "cloudflare"
      volumes: ['./conf/prod:/home/nonroot/.cloudflared']
      command: tunnel run
      restart: unless-stopped
