services:
  # Next.jsの環境
  view-dev:
    container_name: "hnz-view-dev"
    build:
      context: ./view
      dockerfile: Dockerfile
    volumes:
      - ./view:/view
      - ./view/node_modules:/view/node_modules
    ports:
      - "3030:3000"
    stdin_open: true
    tty: true
    env_file:
      - ./view/.env
    restart: unless-stopped
