version: "3"
services:
  # Next.jsの環境
  view:
    container_name: "hnz-view"
    build:
      context: ./view
    volumes:
      - ./view:/view
      - ./view/node_modules:/view/node_modules
    command: sh -c "PORT=3030 npm run dev"
    ports:
      - "3030:3030"
    stdin_open: true
    tty: true
