services:
  # Next.jsの環境
  view-prod:
    container_name: "hnz-view-prod"
    build:
      context: ./view
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true 
    restart: unless-stopped
