version: "3"
services:
  # Next.jsの環境
  hnz-view:
    container_name: "hnz-view"
    build:
      context: ./view
      dockerfile: Dockerfile.prod
    ports:
      - "3030:3030"
    stdin_open: true
    tty: true
