services:
  # Next.jsの環境
  hnz-view:
    container_name: "hnz-view"
    build:
      context: ./view
      dockerfile: Dockerfile.prod
    ports:
      - "3030:3030"
    stdin_open: true
    tty: true 
    env_file:
      - ./view/.env.development.local

  cloudflare:
    image: "cloudflare/cloudflared:latest"
    container_name: "cloudflare"
    volumes: ['./web/prod:/home/nonroot/.cloudflared']
    command: tunnel run
