apiVersion: v1
kind: Service
metadata:
  name: hnz-deployment
  labels:
    app: hnz
spec:
  ports:
    - nodePort: 30001
      port: 3000 # deployment.hnzに合わせる
      protocol: TCP
      targetPort: 3000 # deployment.hnzに合わせる
  selector:
    app: hnz
  type: LoadBalancer

