name: Auto Deploy
run-name: ${{ github.actor }} is deploying
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Deploy on momo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_MOMO}}
          username: ${{ secrets.SSH_USERNAME_MOMO}}
          key: ${{ secrets.SSH_PRIVATE_KEY_MOMO}}
          port: ${{ secrets.SSH_PORT_MOMO}}
          script: |
            cd ~/HNZ-PenlightQuiz
            git pull origin master
            git checkout master
            docker compose up -d
