name: Test Docker Compose File
run-name: ${{ github.actor }} is testing docker compose file
on: push

jobs:
  test:
    name: Test Docker Compose File
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose Build
        run: docker compose -f docker-compose.yml build
      - name: Docker Compose Up
        run: docker compose -f docker-compose.yml up -d
      - name: Yarn Build
        uses: ./
        run: docker compose -f docker-compose.yml exec hnz-view yarn install && yarn build
