# Dockerfile for hnz-view service

# Base image
FROM node:latest

# Set the working directory
WORKDIR /view

# Copy the rest of the application
COPY ./ /view

# Install dependencies
RUN yarn install

# Expose the port
EXPOSE 3030

RUN yarn build

# Default command to run the application
CMD ["PORT=3030 yarn start"]
